openapi: 3.0.3
info:
  title: Animal Network
  description: |-
    Апишка социальной сети 
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://localhost:8282
tags:
  - name: profile
    description: Everything about Profile
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /profile/{profileId}:
    get:
      tags:
        - profile
      summary: Find user profile by ID
      description: Returns a single profile
      operationId: getProfileById
      parameters:
        - name: profileId
          in: path
          description: ID of profile to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Profile'
        '400':
          description: Invalid ID supplied
        '404':
          description: Profile not found
  /editProfile:
    put:
      tags:
        - profile
      summary: Updates a profile in the store with form data
      description: ''
      operationId: updateProfileWithForm
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/Profile'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Profile'
        '400':
          description: Invalid ID supplied
        '404':
          description: Profile not found
components:
  schemas:
    Profile:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: doggie
        status:
          type: string
          example: I am fine
        notes:
          type: string
          example: 'I need sleep'
          items:
            type: string
            xml:
              name: photoUrl
        friends:
          type: array
          items:
            type: integer
        avatar:
          type: string
      xml:
        name: profile
  requestBodies:
    Profile:
      description: Profile object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Profile'
        application/xml:
          schema:
            $ref: '#/components/schemas/Profile'
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header